# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PiAmEAuS24Fchi2vlpuP4lUxSTOXEtBM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

import pickle

data= pd.read_csv('slope.csv')

dataset_X = data.iloc[:,[1, 3, 4, 5]].values
dataset_Y = data.iloc[:,6].values

print(dataset_X)

X = dataset_X
Y = dataset_Y

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 42, stratify = data['Stability'] )

from sklearn.ensemble import RandomForestClassifier
rf_clf=RandomForestClassifier(max_features=='auto')
rf_clf.fit(X_train,Y_train)

#These are the predicted output values
ypred=rf_clf.predict(X_test)

rf_clf.score(X_test, Y_test)

new_data=[[35.0,15.0,0.0,31.0]]
pred=rf_clf.predict(new_data)
pred[0]

pickle.dump(rf_clf, open('model.pkl','wb'))
model = pickle.load(open('model.pkl','rb'))